services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: flask_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://admin:password@db:5432/users_db
    working_dir: /app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]  
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
